name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master', adjust as per your repo

jobs:
  build-deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"  # Optional: skip builds
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Include your PaperMod theme

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build site
        run: hugo --minify --source blogs --destination public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

