name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  build-deploy:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"  # Optional: skip CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Required if using themes as submodules
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Hugo site
        run: hugo --minify --ignoreCache --buildDrafts --buildFuture

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_PAT }}
          publish_dir: ./public
          force_orphan: true  # Ensures a clean gh-pages branch (optional but useful)

